crc32-slice-by-8.c: fix for C90 compilers
crc32_slice_by_8.c:344:3: error: ISO C90 forbids mixed declarations
and code [-Werror=declaration-after-statement]

(cherry picked from commit 23a1d62b2580f9462c02524eb23af99c04ca65d0)