IntegrityError: add placeholder for message, fixes #1572
So that the message we give appears not only in the traceback, but also in the (short) error message.