fix conflict between foo, _ construct and i18n
it turns out that the _() function overlaps with our use of list
expansion constructs. i.e. this doesn't work:

    _ = lambda x: x

    def foo():
        _('test')
        a, _ = (1,2,3)

it raises a:

    UnboundLocalError: local variable '_' referenced before assignment

so we use __() everywhere instead. _() is still available, but we
favor __() by default now.

that was a sucker to figure out.