fix build_man: missing benchmark_cpu.rst
$ python setup.py build_usage && python setup.py build_man
...
building man page borg-benchmark-cpu(1)
error: [Errno 2] No such file or directory: 'docs/usage/benchmark_cpu.rst'