fixup: include xxhash.c
when including .h (as usual), one runs into this:

building 'borg.algorithms.checksums' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/user/w/borg-env/include -I/home/user/.pyenv/versions/3.5.3/include/python3.5m -c src/borg/algorithms/checksums.c -o build/temp.linux-x86_64-3.5/src/borg/algorithms/checksums.o
    src/borg/algorithms/checksums.c:838:17: error: field ‘state’ has incomplete type
       XXH64_state_t state;
                     ^~~~~

when including .c, it works!