Fix Fedora installation instructions
Update installation instructions so that the following error won't occur:

gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
error: command 'gcc' failed with exit status 1